### ISSUE TITLE
when i open it it gets stuck

### ISSUE THREAD

**Issue by jdizzle2k11** [Warkdev/BestInSlotClassic#1]
https://imgur.com/a/aPQNj4h

This is what it gets stuck on when i open it up ingame

Scourge - rogue
i tried changing class/race and it does nothing.

**Comment by Warkdev** [comment]
Hello,

Many thanks for your report! I expected the api to send undead instead of scourge. 

I'll fix this in the coming days. 

Warkdev.

**Comment by Warkdev** [comment]
Hello,

Thank you again for your report, this is really precious as I've a limited time totest all possible combinations :)

This commit should have fixed the bug you've faced (and I'm sorry for that): https://github.com/Warkdev/BestInSlotClassic/commit/ebaab14e876bc631f430264f565875a6b4e75b5a

The v1.0.3 including it should be available shortly on Twitch.

Warkdev
