### ISSUE TITLE
Ability to check if an item is on the BIS list in the tooltip

### ISSUE THREAD

**Issue by roblabla** [Warkdev/BestInSlotClassic#19]
ExoLink BIS has this cool feature that adds to the item tooltip the classes an item is BIS for. This is particularly useful to know at a glance what your BIS items are, and the items that are BIS for other classes, so you know when to need/pass.

![bis](https://user-images.githubusercontent.com/1069318/76166873-593bc500-6162-11ea-96b7-85b02f60eb40.PNG)

It'd be really nice for this addon to sport a similar feature.

**Comment by Warkdev** [comment]
Hello,

Thanks for your feedback, that's right and I had that in mind when creating this issue :)

However, I didn't find yet the right way to manage this. Exolink is using a static list which I don't really like, I'd like to have it more dynamic but it's also pointless to display too much info on the tooltip.

Wark

**Comment by Warkdev** [comment]
https://github.com/Warkdev/BestInSlotClassic/commit/631d02c40e43053eab30d2062711ed13e36d369f
