### ISSUE TITLE
Adding BIS set for Elemental Shaman

### ISSUE THREAD

**Issue by FeldwebelSchultz** [Warkdev/BestInSlotClassic#20]
Hi,
can you please add the BiS for elemental shamans, that would be really nice.
Best regards,
Schultz

BiS Phase 3:
https://de.classic.wowhead.com/guides/wow-classic-elemental-shaman-dps-pre-raid-best-in-slot-gear

https://de.classic.wowhead.com/guides/wow-classic-elemental-shaman-dps-molten-core-best-in-slot-gear

https://classic.wowhead.com/guides/elemental-shaman-dps-gear-bis-classic-wow

**Comment by Warkdev** [comment]
Hello,

I was initially reluctant to add elemental shaman info as I couldn't find any valid theorycraft about it. Icy-veins doesn't give any reason or number why it's like that which made me a bit reluctant to do so. 

If really you'd like to have it, I can see what I can do but the support is then very limited. 😉

**Comment by Warkdev** [comment]
Hello,

I've discussed with some theorycrafter about shaman elemental and they told me that introducing this for them is a very bad idea. The reason being that the theorycraft for shaman depends a lot on your actual equipment, the length of the fight and so on.

Instead, they prefer that you use their spreadsheets and ask questions on their discord. I may add this link in my addon in the future: https://discord.gg/thxqmWd

Wark
