### ISSUE TITLE
Tooltip Error

### ISSUE THREAD

**Issue by Chzconey** [Warkdev/BestInSlotClassic#21]
Date: 2020-03-14 17:48:49
ID: -1
Error occured in: Global
Count: 12
Message: ...terface\AddOns\BestInSlotClassic\modules\tooltip.lua line 480:
   attempt to concatenate local 'invSlot' (a nil value)
Debug:
   [C]: ?
   ...terface\AddOns\BestInSlotClassic\modules\tooltip.lua:480:
      ...terface\AddOns\BestInSlotClassic\modules\tooltip.lua:466
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?

**Comment by Warkdev** [comment]
Hi,

I've noticed it too. I'm pushing an update at the moment.

Wark
