### ISSUE TITLE
Owned Raid BIS shown in Dungeon BIS

### ISSUE THREAD

**Issue by chrisblossom** [Warkdev/BestInSlotClassic#23]
If the character has one of the best in slot items for raid, that item should be shown when checking dungeon bis list.

I think this should default on, but be toggle-able so you can check the list for other characters.

For example:

`Raid BIS:`
<img width="254" alt="raid-bis" src="https://user-images.githubusercontent.com/1595871/77589150-6669eb00-6ea8-11ea-9564-9aa7cfb9c9db.png">

`Pre-Raid BIS:`
<img width="214" alt="pre-bis" src="https://user-images.githubusercontent.com/1595871/77589146-64a02780-6ea8-11ea-8f42-cde6f2c71c76.png">

`Band of Dark Dominion` should show up on `Pre-Raid BIS`.

**Comment by Warkdev** [comment]
Will be implemented in 2.4.

**Comment by Warkdev** [comment]
Implemented in release: https://github.com/Warkdev/BestInSlotClassic/commit/ec3eaf3b14c0fa4466fccdbcc31e39cbdf4154b1
