### ISSUE TITLE
no information bug

### ISSUE THREAD

**Issue by 1Mahabone** [Warkdev/BestInSlotClassic#25]
Date: 2020-03-26 18:38:29
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\BestInSlotClassic\modules\manager.lua line 374:
   attempt to perform arithmetic on upvalue 'selectedRank' (a nil value)
Debug:
   ...terface\AddOns\BestInSlotClassic\modules\manager.lua:374:
      ...terface\AddOns\BestInSlotClassic\modules\manager.lua:360
   ...terface\AddOns\BestInSlotClassic\modules\manager.lua:825: ShowManager()
   ...terface\AddOns\BestInSlotClassic\modules\minimap.lua:9: OnClick()
   ...tlasLootClassic\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:144:
      ...tlasLootClassic\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142
Locals:
temp = nil
count = 0
(*temporary) = <function> defined @Interface\AddOns\BestInSlotClassic\modules\sql.lua:97
(*temporary) = <table> {
 OnTooltipSetSpell = <function> defined @Interface\AddOns\BestInSlotClassic\modules\tooltip.lua:103
 CreateCheckBox = <function> defined @Interface\AddOns\BestInSlotClassic\modules\widgets.lua:67
 GetLocalizedReputationLevel = <function> defined @Interface\AddOns\BestInSlotClassic\modules\locales.lua:32
 OpenConfigPane = <function> defined @Interface\AddOns\BestInSlotClassic\modules\cli.lua:6
 ResetDefaults = <function> defined @Interface\AddOns\BestInSlotClassic\core.lua:66
 OnGameTooltipSetItem = <function> defined @Interface\AddOns\BestInSlotClassic\modules\tooltip.lua:474
 SearchBis = <function> defined @Interface\AddOns\BestInSlotClassic\modules\sql.lua:97
 SetUILocale = <function> defined @Interface\AddOns\BestInSlotClassic\modules\locales.lua:78
 ShowManager = <function> defined @Interface\AddOns\BestInSlotClassic\modules\manager.lua:647
 UpdateMinimapIcon = <function> defined @Interface\AddOns\BestInSlotClassic\modules\minimap.lua:32
 CreateClickableIconFrame = <function> defined @Interface\AddOns\BestInSlotClassic\modules\manager.lua:615
 FallbackLocale = <function> defined @Interface\AddOns\BestInSlotClassic\modules\locales.lua:56
 SearchBisEnchant = <function> defined @Interface\AddOns\BestInSlotClassic\modules\sql.lua:23
 CreateWindow = <function> defined @Interface\AddOns\BestInSlotClassic\modules\widgets.lua:41
 GetLocalizedFactionName = <function> defined @Interface\AddOns\BestInSlotClassic\modules\locales.lua:23
 CreateSlider = <function> defined @Interface\AddOns\BestInSlotClassic\modules\widgets.lua:78
 LoadPlayerInfo = <function> defined @Interface\AddOns\BestInSlotClassic\core.lua:78
 CreateMinimapIcon = <function> defined @Interface\AddOns\BestInSlotClassic\modules\minimap.lua:20
 LoadAllItems = <function> defined @Interface\AddOns\BestInSlotClassic\modules\sql.lua:17
 OnTooltipSetItem = <function> defined @Interface\AddOns\BestInSlotClassic\modules\tooltip.lua:116
 CreateTextFrame = <function> defined @Interface\AddOns\BestInSlotClassic\modules\manager.lua:635
 CreateSettingsInterface = <function> defined @Interface\AddOns\BestInSlotClassic\modules\bisc_options.lua:41
 GetLocalizedMapName = <function> defined @Interface\AddOns\BestInSlotClassic\modules\locales.lua:10
 CreateGameTooltip = <function> defined @Interface\AddOns\BestInSlotClassic\modules\tooltip.lua:462
 containsValue = <function> defined @Interface\AddOns\BestInSlotClassic\modules\sql.lua:8
 CreateIconFrame = <function> defined @Interface\AddOns\BestInSlotClassic\modules\manager.lua:600
 HandleLogLevel = <function> defined @Interface\AddOns\BestInSlotClassic\modules\cli.lua:22
 UpdateIcon = <function> defined @Interface\AddOns\BestInSlotClassic\modules\manager.lua:592
 LoadItemInfo = <function> defined @Interface\AddOns\BestInSlotClassic\core.lua:72
 GetUILocale = <function> defined @Interface\AddOns\BestInSlotClassic\modules\locales.lua:86
 SetValues = <function> defined @Interface\AddOns\BestInSlotClassic\modules\bisc_options.lua:87
 PrintPlayerInfo = <function> defined @Interface\AddOns\BestInSlotClassic\core.lua:160
 logmsg = <function> defined @Interface\AddOns\BestInSlotClassic\modules\bis_logger.lua:15
}
(*temporary) = "Alliance"
(*temporary) = 1
(*temporary) = 4
(*temporary) = 3
(*temporary) = 1
(*temporary) = nil
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 6
(*temporary) = 7
(*temporary) = nil
(*temporary) = "_"
(*temporary) = "11"
(*temporary) = "attempt to perform arithmetic on upvalue 'selectedRank' (a nil value)"
ResetUI = <function> defined @Interface\AddOns\BestInSlotClassic\modules\manager.lua:195
selectedRace = 1
selectedClass = 4
selectedSpec = 1
selectedPhase = 3
selectedMagicResist = 1
twoHands = false
raid = nil
worldBoss = nil
pvp = nil
selectedRank = nil
characterHasItem = <function> defined @Interface\AddOns\BestInSlotClassic\modules\manager.lua:343
charact
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AllyRoute, v1.1
  AtlasLootClassic, vv1.4.7
  AtlasLootClassicData, vv1.4.7
  AtlasLootClassicDungeonsAndRaids, vv1.4.7
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.5
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BestInSlotClassic, v2.3
  DBMCore, v1.13.41
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixMaps, v1.13.55
  Questie, v5.10.0 0 fd3ff918
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v1.3.1
  TomTom, vv11304-1.1.2
  VendorPrice, v1.3.4
  WeakAuras, v2.16.6
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=4ed)

**Comment by DanielRourke** [comment]
this breaks the addon completely
it appears to be and issue when first using the addon when a random rank is selected it works fine for all other toons
in the function Update() the 374 has the statement selectedRank - 4 when selectedRank appears to be null

**Comment by Warkdev** [comment]
Hello,

Indeed, it has been reported several times already, it will be fixed in 2.4 which I'm expecting to release tonight or tomorrow. :)

Wark

**Comment by Warkdev** [comment]
Fixed by release: https://github.com/Warkdev/BestInSlotClassic/commit/ec3eaf3b14c0fa4466fccdbcc31e39cbdf4154b1
