### ISSUE TITLE
FPS drops

### ISSUE THREAD

**Issue by SpeedySaky** [Warkdev/BestInSlotClassic#27]
is there any way to stop fps drops when using addon because i usually play around 200 fps,ofc not needed 200,but i leave at max possible but when i enable addon i goes under 40 fps but i done get any lua error
is it because of huge database and can it be somehow fixed because i really like the addon

**Comment by Warkdev** [comment]
Hey welcome here.

Which version are you using? Normally, the performance improved a lot as from 2.4.0 for the tooltip. 

Wark
