### ISSUE TITLE
Lua Error with New Update

### ISSUE THREAD

**Issue by Chzconey** [Warkdev/BestInSlotClassic#28]
Message: Interface\AddOns\BestInSlotClassic\locales\ptBR\lookupObjects.lua:983: '}' expected (to close '{' at line 1) near '['
Time: Wed Apr  1 14:38:59 2020
Count: 4

**Comment by Warkdev** [comment]
Yes I've seen that one and I've removed the current version from twitch.

Please revert meanwhile to the previous one.
